/*
 * motor_driver.h
 *
 *  Created on: Feb 3, 2025
 *      Author: A
 */

#ifndef INC_MOTOR_DRIVER_H_
#define INC_MOTOR_DRIVER_H_

#include "stm32f1xx_hal.h"  // Include the HAL library for STM32
#include "stm32f1xx_hal_tim.h"            // Include the Timer header generated by CubeMX

// Function prototypes
void Motor_Init(void);                          // Initialize the motor driver
void Motor1_Forward(uint16_t speed);            // Move Motor 1 forward at specified speed
void Motor1_Backward(uint16_t speed);           // Move Motor 1 backward at specified speed
void Motor2_Forward(uint16_t speed);            // Move Motor 2 forward at specified speed
void Motor2_Backward(uint16_t speed);           // Move Motor 2 backward at specified speed
void Motor1_Stop(void);                         // Stop Motor 1
void Motor2_Stop(void);                         // Stop Motor 2
void Motor_Turn(uint16_t speed, uint8_t direction);  // Turn the car left or right

// Direction constants for turning
#define TURN_LEFT  0
#define TURN_RIGHT 1

#endif /* INC_MOTOR_DRIVER_H_ */
