name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # 1) Register QEMU emulators so ARM binaries run under emulation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64

    # 2) Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      run: |
        docker login -u halem10 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push the Docker image of lane_detection for arm64
      run: docker buildx build --platform linux/arm64 -t halem10/lane_detection:1.3 --push -f AI_Features/Docker/lane_detection/DockerFile AI_Features/Docker/lane_detection/
    
      

