name: Docker Image CI for sign feature

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repo
      - uses: actions/checkout@v4

      # 2) Register QEMU emulators so ARM binaries run under emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      # 3) Set up Docker Buildx (for multi‑arch build support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: halem10
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 5) Build & push using docker-compose
      - name: Build & push with Docker Compose
        working-directory: AI_Features/Docker/Sign_Feature
        run: |
          # Ensure Compose V2 is used (`docker compose` vs `docker-compose` if needed)
          docker-compose version

          # Build your service(s) using the ARM64 platform
          docker-compose build --parallel

          # Push the built image(s) to Docker Hub
          docker-compose push
